version: '3'

services:
  nginx:
    image: nginx:1.15.5-alpine
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs/:/var/log/nginx/
    ports:
      - ${APP_PORT:-0}:80
    depends_on:
      - php

  php:
    build: docker/php/fpm
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
